---
- name: apache restart
  service: name=apache2 state=restarted
  become: true
  become_method: sudo

- name: nginx restart
  service: name=nginx state=restarted
  become: true
  become_method: sudo
